[package]
name = "norminette_lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "0.7.7"
lsp-types = "0.97.0"
nom = "7.1.3"
serde_json = "1.0.128"
tracing-subscriber = "0.3.18"
serde = "1.0.210"
